---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/overland/batches":
    post:
      summary: Creates a batch of points
      tags:
      - Batches
      parameters:
      - name: api_key
        in: query
        required: true
        description: API Key
        schema:
          type: string
      responses:
        '201':
          description: Batch of points created
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                geometry:
                  type: object
                  properties:
                    type:
                      type: string
                    coordinates:
                      type: array
                properties:
                  type: object
                  properties:
                    timestamp:
                      type: string
                    altitude:
                      type: number
                    speed:
                      type: number
                    horizontal_accuracy:
                      type: number
                    vertical_accuracy:
                      type: number
                    motion:
                      type: array
                    pauses:
                      type: boolean
                    activity:
                      type: string
                    desired_accuracy:
                      type: number
                    deferred:
                      type: number
                    significant_change:
                      type: string
                    locations_in_payload:
                      type: number
                    device_id:
                      type: string
                    wifi:
                      type: string
                    battery_state:
                      type: string
                    battery_level:
                      type: number
                required:
                - geometry
                - properties
            examples:
              '0':
                summary: Creates a batch of points
                value:
                  locations:
                  - type: Feature
                    geometry:
                      type: Point
                      coordinates:
                      - 13.356718
                      - 52.502397
                    properties:
                      timestamp: '2021-06-01T12:00:00Z'
                      altitude: 0
                      speed: 0
                      horizontal_accuracy: 0
                      vertical_accuracy: 0
                      motion: []
                      pauses: false
                      activity: unknown
                      desired_accuracy: 0
                      deferred: 0
                      significant_change: unknown
                      locations_in_payload: 1
                      device_id: Swagger
                      wifi: unknown
                      battery_state: unknown
                      battery_level: 0
  "/api/v1/owntracks/points":
    post:
      summary: Creates a point
      tags:
      - Points
      parameters:
      - name: api_key
        in: query
        required: true
        description: API Key
        schema:
          type: string
      responses:
        '200':
          description: Point created
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                batt:
                  type: number
                lon:
                  type: number
                acc:
                  type: number
                bs:
                  type: number
                inrids:
                  type: array
                BSSID:
                  type: string
                SSID:
                  type: string
                vac:
                  type: number
                inregions:
                  type: array
                lat:
                  type: number
                topic:
                  type: string
                t:
                  type: string
                conn:
                  type: string
                m:
                  type: number
                tst:
                  type: number
                alt:
                  type: number
                _type:
                  type: string
                tid:
                  type: string
                _http:
                  type: boolean
                ghash:
                  type: string
                isorcv:
                  type: string
                isotst:
                  type: string
                disptst:
                  type: string
              required:
              - owntracks/jane
            examples:
              '0':
                summary: Creates a point
                value:
                  batt: 85
                  lon: -74.006
                  acc: 8
                  bs: 2
                  inrids:
                  - 5f1d1b
                  BSSID: b0:f2:8:45:94:33
                  SSID: Home Wifi
                  vac: 3
                  inregions:
                  - home
                  lat: 40.7128
                  topic: owntracks/jane/iPhone 12 Pro
                  t: p
                  conn: w
                  m: 1
                  tst: 1706965203
                  alt: 41
                  _type: location
                  tid: RO
                  _http: true
                  ghash: u33d773
                  isorcv: '2024-02-03T13:00:03Z'
                  isotst: '2024-02-03T13:00:03Z'
                  disptst: '2024-02-03 13:00:03'
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
